export const INDIA_STATES = {
    "Odisha": { lang: "Odia, English", std: "0674, 0661", capital: "Bhubaneswar" },
    "Andhra Pradesh": { lang: "Telugu, Urdu", std: "0866, 0891", capital: "Amaravati" },
    "Arunachal Pradesh": { lang: "English, Nyishi", std: "0360", capital: "Itanagar" },
    "Assam": { lang: "Assamese, Bengali", std: "0361", capital: "Dispur" },
    "Bihar": { lang: "Hindi, Maithili", std: "0612", capital: "Patna" },
    "Chhattisgarh": { lang: "Chhattisgarhi, Hindi", std: "0771", capital: "Raipur" },
    "Goa": { lang: "Konkani, Marathi", std: "0832", capital: "Panaji" },
    "Gujarat": { lang: "Gujarati, Hindi", std: "079", capital: "Gandhinagar" },
    "Haryana": { lang: "Hindi, Punjabi", std: "0172", capital: "Chandigarh" },
    "Himachal Pradesh": { lang: "Hindi, Pahari", std: "0177", capital: "Shimla" },
    "Jharkhand": { lang: "Hindi, Santali", std: "0651", capital: "Ranchi" },
    "Karnataka": { lang: "Kannada", std: "080", capital: "Bengaluru" },
    "Kerala": { lang: "Malayalam", std: "0471, 0484", capital: "Thiruvananthapuram" },
    "Madhya Pradesh": { lang: "Hindi", std: "0755", capital: "Bhopal" },
    "Maharashtra": { lang: "Marathi", std: "022, 020", capital: "Mumbai" },
    "Manipur": { lang: "Meitei", std: "0385", capital: "Imphal" },
    "Meghalaya": { lang: "English, Khasi", std: "0364", capital: "Shillong" },
    "Mizoram": { lang: "Mizo, English", std: "0389", capital: "Aizawl" },
    "Nagaland": { lang: "English", std: "0370", capital: "Kohima" },
    "Punjab": { lang: "Punjabi", std: "0172, 0161", capital: "Chandigarh" },
    "Rajasthan": { lang: "Hindi, Rajasthani", std: "0141", capital: "Jaipur" },
    "Sikkim": { lang: "Nepali, Sikkimese", std: "03592", capital: "Gangtok" },
    "Tamil Nadu": { lang: "Tamil", std: "044, 0422", capital: "Chennai" },
    "Telangana": { lang: "Telugu, Urdu", std: "040", capital: "Hyderabad" },
    "Tripura": { lang: "Bengali, Kokborok", std: "0381", capital: "Agartala" },
    "Uttar Pradesh": { lang: "Hindi, Urdu", std: "0522, 0120", capital: "Lucknow" },
    "Uttarakhand": { lang: "Hindi, Sanskrit", std: "0135", capital: "Dehradun" },
    "West Bengal": { lang: "Bengali, English", std: "033", capital: "Kolkata" },
    "Delhi": { lang: "Hindi, Punjabi, English", std: "011", capital: "New Delhi" }
};

export const WORLD_COUNTRIES = {
    "in": { lang: "Hindi, English", code: "+91", currency: "INR" },
    "us": { lang: "English", code: "+1", currency: "USD" },
    "gb": { lang: "English", code: "+44", currency: "GBP" },
    "fr": { lang: "French", code: "+33", currency: "EUR" },
    "de": { lang: "German", code: "+49", currency: "EUR" },
    "jp": { lang: "Japanese", code: "+81", currency: "JPY" },
    "cn": { lang: "Chinese", code: "+86", currency: "CNY" },
    "ru": { lang: "Russian", code: "+7", currency: "RUB" },
    "br": { lang: "Portuguese", code: "+55", currency: "BRL" },
    "au": { lang: "English", code: "+61", currency: "AUD" },
    "ca": { lang: "English, French", code: "+1", currency: "CAD" }
};
